import React from 'react';
import { useNavigate } from 'react-router-dom';
import './Landing.css';

const Landing = () => {
    const navigate = useNavigate();

    return (
        <div className="landing-container">
            <div className="landing-bg-pattern"></div>
            <div className="landing-accent accent-1"></div>
            <div className="landing-accent accent-2"></div>
            <nav className="landing-nav">
                <div className="nav-logo">VidNotes AI</div>
                <div className="nav-links">
                    <button className="nav-btn" onClick={() => navigate('/login')}>Login</button>
                    <button className="nav-btn primary" onClick={() => navigate('/signup')}>Sign Up</button>
                </div>
            </nav>

            <header className="landing-hero">
                <h1 className="hero-title">
                    Transform YouTube Videos <br />
                    Into <span className="text-highlight">Smart Study Notes</span>
                </h1>
                <p className="hero-subtitle">
                    Paste any YouTube video link and let our AI extract transcripts,
                    generate concise summaries, and create structured study notes in seconds.
                </p>
                <div className="hero-actions">
                    <button className="btn-large btn-primary" onClick={() => navigate('/signup')}>
                        Get Started Free
                    </button>
                </div>
            </header>
            <section className="landing-features">
                <div className="features-grid">
                    <div className="feature-card">
                        <div className="feature-icon">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                <polygon points="5 3 19 12 5 21 5 3"></polygon>
                            </svg>
                        </div>
                        <h3 className="feature-title">Video Transcript Extraction</h3>
                        <p className="feature-desc">Automatically extract and process transcripts from any YouTube video with just a link.</p>
                    </div>
                    <div className="feature-card">
                        <div className="feature-icon">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                                <polyline points="14 2 14 8 20 8"></polyline>
                                <line x1="16" y1="13" x2="8" y2="13"></line>
                                <line x1="16" y1="17" x2="8" y2="17"></line>
                            </svg>
                        </div>
                        <h3 className="feature-title">AI-Powered Summaries</h3>
                        <p className="feature-desc">Get clear, concise summaries generated by advanced LLM technology in seconds.</p>
                    </div>
                    <div className="feature-card">
                        <div className="feature-icon">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                                <path d="M12 20h9"></path>
                                <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path>
                            </svg>
                        </div>
                        <h3 className="feature-title">Structured Study Notes</h3>
                        <p className="feature-desc">Receive well-organized bullet points and key takeaways ready for studying.</p>
                    </div>
                </div>
            </section>
            <footer className="landing-footer">
                <p>© 2026 VidNotes AI. All rights reserved.</p>
            </footer>
        </div>
    );
};

export default Landing;
